CREATE TABLE public."anotherTable" (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public."anotherTable" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."anotherTable" ADD CONSTRAINT "anotherTable_pkey" PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public."anotherTable" TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public."anotherTable" TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public."anotherTable" TO service_role;
