CREATE TABLE public."testTable" (id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public."testTable" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."testTable" ADD CONSTRAINT "testTable_pkey" PRIMARY KEY (id);
GRANT ALL ON public."testTable" TO anon;
GRANT ALL ON public."testTable" TO authenticated;
GRANT ALL ON public."testTable" TO service_role;
